spring:
  application:
    name: Server
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8000

provider:
  mtc:
    url: http://localhost:8020
  alfa:
    url: http://localhost:8010